{{ if eq .Values.global.timeseriesLocation "on-cluster"}}
apiVersion: v1
kind: Secret
metadata:
  name: timeseries-creds
  labels:
    app: drycc-timeseries
    heritage: drycc
  annotations:
    "helm.sh/hook": pre-install
data:
  superuser: {{ if .Values.superuser | default "" | ne "" }}{{ .Values.superuser | lower | b64enc }}{{ else }}{{ randAlpha 32 | lower | b64enc }}{{ end }}
  superuser-password: {{ if .Values.superuserPassword | default "" | ne "" }}{{ .Values.superuserPassword | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  replicator: {{ if .Values.replicator | default "" | ne "" }}{{ .Values.replicator | lower | b64enc }}{{ else }}{{ randAlpha 32 | lower | b64enc }}{{ end }}
  replicator-password: {{ if .Values.replicatorPassword | default "" | ne "" }}{{ .Values.replicatorPassword | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
  user: {{ if .Values.user | default "" | ne "" }}{{ .Values.user | lower | b64enc }}{{ else }}{{ randAlpha 32 | lower | b64enc }}{{ end }}
  password: {{ if .Values.password | default "" | ne "" }}{{ .Values.password | b64enc }}{{ else }}{{ randAlphaNum 32 | b64enc }}{{ end }}
{{- end }}
