{{- if eq .Values.global.timeseriesLocation "on-cluster" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s:drycc-timeseries" .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s:drycc-timeseries" .Release.Namespace | quote }}
subjects:
- kind: ServiceAccount
  name: drycc-timeseries
  namespace: {{ .Release.Namespace }}
{{- end }}
